name: Good First Issue Candidate
description: Suggest an idea for this project
labels: [ "Good First Issue Candidate" ]
type: Feature
body:
  - type: markdown
    attributes:
      value: |
        ## Thanks for submitting a Good First Issue!
        
        This issue targets first time contributors to [Paladin](https://lfdt-paladin.github.io/paladin/head/).
        We know that creating a pull request (PR) is a major barrier for new contributors.
        The goal of this issue (and all other issues labeled with) [**'Good First Issue'**](https://github.com/issues?q=is%3Aopen+is%3Aissue+org%3ALFDT-Paladin+archived%3Afalse+label%3A%22good+first+issue%22+) is to help you make your first contribution to Paladin.
        Before submitting:
        * Try searching the existing issues and discussions to see if something similar has been discussed previously.
        * Try opening a GitHub discussion first to gather feedback and reach consensus.
        * If this is a major enhancement, please open a Feature Request.
        ------
  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What is the problem you are trying to solve?
      placeholder: |
        AT THIS SECTION YOU NEED TO DESCRIBE THE ISSUE IN A WAY THAT IS UNDERSTANDABLE TO NEW CONTRIBUTORS.
        YOU MUST NOT ASSUME THAT SUCH CONTRIBUTORS HAVE ANY KNOWLEDGE ABOUT THE CODEBASE OR PALADIN.
        IT IS HELPFUL TO ADD LINKS TO THE RELEVANT DOCUMENTATION AND/OR CODE SECTIONS.
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: What solution do you propose to solve the problem?
      placeholder: |
        AT THIS SECTION YOU NEED TO DESCRIBE THE STEPS NEEDED TO SOLVE THE ISSUE.
        PLEASE BREAK DOWN THE STEPS AS MUCH AS POSSIBLE AND MAKE SURE THAT THEY ARE EASY TO FOLLOW.
        IF POSSIBLE, ADD LINKS TO THE RELEVANT DOCUMENTATION AND/OR CODE SECTIONS.
    validations:
      required: true
  - type: textarea
    id: Implementation
    attributes:
      label: Implementation
      description: What technical steps need to be taken?
      placeholder: |
        AT THIS SECTION YOU NEED TO DESCRIBE THE TECHNICAL STEPS NEEDED TO SOLVE THE ISSUE.
        PLEASE BREAK DOWN THE STEPS AS MUCH AS POSSIBLE AND MAKE SURE THAT THEY ARE EASY TO FOLLOW.
        IF POSSIBLE, ADD LINKS TO THE RELEVANT DOCUMENTATION AND/OR CODE.
  - type: markdown
    attributes:
      value: |
        ------
        
        ## Making Contributions
        
        If you have never contributed to an open source project at GitHub, the following step-by-step guide will introduce you to the workflow.
        A more detailed general documentation of the GitHub PR workflow can be found [here](https://github.com/firstcontributions/first-contributions/blob/master/README.md).
        
        - [ ] **Claim this issue:** Comment below that you are interested in working on the issue
        - [ ] **Wait for assignment:** A community member with the given rights will add you as an assignee of the issue
        - [ ] **Work on the issue:** Follow the detailed description in our [CONTRIBUTING.md](https://github.com/LFDT-Paladin/.github/blob/main/CONTRIBUTING.md) file.
        - [ ] **You did it 🎉:** We will merge the fix in the main branch. Thanks for being part of the Paladin community as an open-source contributor!
        ------
  - type: markdown
    attributes:
      value: |
        ## Additional Questions
        
        If you have any questions about the topic of this issue, please ask us directly by adding a comment below.
        Additionally, we invite you to join our community on our [Discord](https://discord.com/channels/905194001349627914/1303371167020879903).
        
        A general manual about open-source contributions can be found [here](https://github.com/firstcontributions/first-contributions/blob/master/README.md).
