// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package coordinator

import (
	"context"
	"time"

	"github.com/LFDT-Paladin/paladin/core/internal/sequencer/common"
	"github.com/LFDT-Paladin/paladin/core/internal/sequencer/coordinator/transaction"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockCoordinator creates a new instance of MockCoordinator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCoordinator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCoordinator {
	mock := &MockCoordinator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCoordinator is an autogenerated mock type for the Coordinator type
type MockCoordinator struct {
	mock.Mock
}

type MockCoordinator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCoordinator) EXPECT() *MockCoordinator_Expecter {
	return &MockCoordinator_Expecter{mock: &_m.Mock}
}

// GetActiveCoordinatorNode provides a mock function for the type MockCoordinator
func (_mock *MockCoordinator) GetActiveCoordinatorNode(ctx context.Context, initIfNoActiveCoordinator bool) string {
	ret := _mock.Called(ctx, initIfNoActiveCoordinator)

	if len(ret) == 0 {
		panic("no return value specified for GetActiveCoordinatorNode")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(context.Context, bool) string); ok {
		r0 = returnFunc(ctx, initIfNoActiveCoordinator)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockCoordinator_GetActiveCoordinatorNode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetActiveCoordinatorNode'
type MockCoordinator_GetActiveCoordinatorNode_Call struct {
	*mock.Call
}

// GetActiveCoordinatorNode is a helper method to define mock.On call
//   - ctx context.Context
//   - initIfNoActiveCoordinator bool
func (_e *MockCoordinator_Expecter) GetActiveCoordinatorNode(ctx interface{}, initIfNoActiveCoordinator interface{}) *MockCoordinator_GetActiveCoordinatorNode_Call {
	return &MockCoordinator_GetActiveCoordinatorNode_Call{Call: _e.mock.On("GetActiveCoordinatorNode", ctx, initIfNoActiveCoordinator)}
}

func (_c *MockCoordinator_GetActiveCoordinatorNode_Call) Run(run func(ctx context.Context, initIfNoActiveCoordinator bool)) *MockCoordinator_GetActiveCoordinatorNode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 bool
		if args[1] != nil {
			arg1 = args[1].(bool)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCoordinator_GetActiveCoordinatorNode_Call) Return(s string) *MockCoordinator_GetActiveCoordinatorNode_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockCoordinator_GetActiveCoordinatorNode_Call) RunAndReturn(run func(ctx context.Context, initIfNoActiveCoordinator bool) string) *MockCoordinator_GetActiveCoordinatorNode_Call {
	_c.Call.Return(run)
	return _c
}

// GetCurrentState provides a mock function for the type MockCoordinator
func (_mock *MockCoordinator) GetCurrentState() State {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetCurrentState")
	}

	var r0 State
	if returnFunc, ok := ret.Get(0).(func() State); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(State)
	}
	return r0
}

// MockCoordinator_GetCurrentState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCurrentState'
type MockCoordinator_GetCurrentState_Call struct {
	*mock.Call
}

// GetCurrentState is a helper method to define mock.On call
func (_e *MockCoordinator_Expecter) GetCurrentState() *MockCoordinator_GetCurrentState_Call {
	return &MockCoordinator_GetCurrentState_Call{Call: _e.mock.On("GetCurrentState")}
}

func (_c *MockCoordinator_GetCurrentState_Call) Run(run func()) *MockCoordinator_GetCurrentState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCoordinator_GetCurrentState_Call) Return(state State) *MockCoordinator_GetCurrentState_Call {
	_c.Call.Return(state)
	return _c
}

func (_c *MockCoordinator_GetCurrentState_Call) RunAndReturn(run func() State) *MockCoordinator_GetCurrentState_Call {
	_c.Call.Return(run)
	return _c
}

// GetTransactionByID provides a mock function for the type MockCoordinator
func (_mock *MockCoordinator) GetTransactionByID(ctx context.Context, txID uuid.UUID) *transaction.Transaction {
	ret := _mock.Called(ctx, txID)

	if len(ret) == 0 {
		panic("no return value specified for GetTransactionByID")
	}

	var r0 *transaction.Transaction
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *transaction.Transaction); ok {
		r0 = returnFunc(ctx, txID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*transaction.Transaction)
		}
	}
	return r0
}

// MockCoordinator_GetTransactionByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTransactionByID'
type MockCoordinator_GetTransactionByID_Call struct {
	*mock.Call
}

// GetTransactionByID is a helper method to define mock.On call
//   - ctx context.Context
//   - txID uuid.UUID
func (_e *MockCoordinator_Expecter) GetTransactionByID(ctx interface{}, txID interface{}) *MockCoordinator_GetTransactionByID_Call {
	return &MockCoordinator_GetTransactionByID_Call{Call: _e.mock.On("GetTransactionByID", ctx, txID)}
}

func (_c *MockCoordinator_GetTransactionByID_Call) Run(run func(ctx context.Context, txID uuid.UUID)) *MockCoordinator_GetTransactionByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCoordinator_GetTransactionByID_Call) Return(transaction1 *transaction.Transaction) *MockCoordinator_GetTransactionByID_Call {
	_c.Call.Return(transaction1)
	return _c
}

func (_c *MockCoordinator_GetTransactionByID_Call) RunAndReturn(run func(ctx context.Context, txID uuid.UUID) *transaction.Transaction) *MockCoordinator_GetTransactionByID_Call {
	_c.Call.Return(run)
	return _c
}

// QueueEvent provides a mock function for the type MockCoordinator
func (_mock *MockCoordinator) QueueEvent(ctx context.Context, event common.Event) {
	_mock.Called(ctx, event)
	return
}

// MockCoordinator_QueueEvent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'QueueEvent'
type MockCoordinator_QueueEvent_Call struct {
	*mock.Call
}

// QueueEvent is a helper method to define mock.On call
//   - ctx context.Context
//   - event common.Event
func (_e *MockCoordinator_Expecter) QueueEvent(ctx interface{}, event interface{}) *MockCoordinator_QueueEvent_Call {
	return &MockCoordinator_QueueEvent_Call{Call: _e.mock.On("QueueEvent", ctx, event)}
}

func (_c *MockCoordinator_QueueEvent_Call) Run(run func(ctx context.Context, event common.Event)) *MockCoordinator_QueueEvent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 common.Event
		if args[1] != nil {
			arg1 = args[1].(common.Event)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCoordinator_QueueEvent_Call) Return() *MockCoordinator_QueueEvent_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockCoordinator_QueueEvent_Call) RunAndReturn(run func(ctx context.Context, event common.Event)) *MockCoordinator_QueueEvent_Call {
	_c.Run(run)
	return _c
}

// SelectActiveCoordinatorNode provides a mock function for the type MockCoordinator
func (_mock *MockCoordinator) SelectActiveCoordinatorNode(ctx context.Context) (string, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for SelectActiveCoordinatorNode")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (string, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) string); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCoordinator_SelectActiveCoordinatorNode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SelectActiveCoordinatorNode'
type MockCoordinator_SelectActiveCoordinatorNode_Call struct {
	*mock.Call
}

// SelectActiveCoordinatorNode is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockCoordinator_Expecter) SelectActiveCoordinatorNode(ctx interface{}) *MockCoordinator_SelectActiveCoordinatorNode_Call {
	return &MockCoordinator_SelectActiveCoordinatorNode_Call{Call: _e.mock.On("SelectActiveCoordinatorNode", ctx)}
}

func (_c *MockCoordinator_SelectActiveCoordinatorNode_Call) Run(run func(ctx context.Context)) *MockCoordinator_SelectActiveCoordinatorNode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCoordinator_SelectActiveCoordinatorNode_Call) Return(s string, err error) *MockCoordinator_SelectActiveCoordinatorNode_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockCoordinator_SelectActiveCoordinatorNode_Call) RunAndReturn(run func(ctx context.Context) (string, error)) *MockCoordinator_SelectActiveCoordinatorNode_Call {
	_c.Call.Return(run)
	return _c
}

// Stop provides a mock function for the type MockCoordinator
func (_mock *MockCoordinator) Stop() {
	_mock.Called()
	return
}

// MockCoordinator_Stop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stop'
type MockCoordinator_Stop_Call struct {
	*mock.Call
}

// Stop is a helper method to define mock.On call
func (_e *MockCoordinator_Expecter) Stop() *MockCoordinator_Stop_Call {
	return &MockCoordinator_Stop_Call{Call: _e.mock.On("Stop")}
}

func (_c *MockCoordinator_Stop_Call) Run(run func()) *MockCoordinator_Stop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCoordinator_Stop_Call) Return() *MockCoordinator_Stop_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockCoordinator_Stop_Call) RunAndReturn(run func()) *MockCoordinator_Stop_Call {
	_c.Run(run)
	return _c
}

// UpdateOriginatorNodePool provides a mock function for the type MockCoordinator
func (_mock *MockCoordinator) UpdateOriginatorNodePool(ctx context.Context, originatorNode string) {
	_mock.Called(ctx, originatorNode)
	return
}

// MockCoordinator_UpdateOriginatorNodePool_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateOriginatorNodePool'
type MockCoordinator_UpdateOriginatorNodePool_Call struct {
	*mock.Call
}

// UpdateOriginatorNodePool is a helper method to define mock.On call
//   - ctx context.Context
//   - originatorNode string
func (_e *MockCoordinator_Expecter) UpdateOriginatorNodePool(ctx interface{}, originatorNode interface{}) *MockCoordinator_UpdateOriginatorNodePool_Call {
	return &MockCoordinator_UpdateOriginatorNodePool_Call{Call: _e.mock.On("UpdateOriginatorNodePool", ctx, originatorNode)}
}

func (_c *MockCoordinator_UpdateOriginatorNodePool_Call) Run(run func(ctx context.Context, originatorNode string)) *MockCoordinator_UpdateOriginatorNodePool_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCoordinator_UpdateOriginatorNodePool_Call) Return() *MockCoordinator_UpdateOriginatorNodePool_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockCoordinator_UpdateOriginatorNodePool_Call) RunAndReturn(run func(ctx context.Context, originatorNode string)) *MockCoordinator_UpdateOriginatorNodePool_Call {
	_c.Run(run)
	return _c
}

// NewMockEvent creates a new instance of MockEvent. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEvent(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEvent {
	mock := &MockEvent{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockEvent is an autogenerated mock type for the Event type
type MockEvent struct {
	mock.Mock
}

type MockEvent_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEvent) EXPECT() *MockEvent_Expecter {
	return &MockEvent_Expecter{mock: &_m.Mock}
}

// GetEventTime provides a mock function for the type MockEvent
func (_mock *MockEvent) GetEventTime() time.Time {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetEventTime")
	}

	var r0 time.Time
	if returnFunc, ok := ret.Get(0).(func() time.Time); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(time.Time)
	}
	return r0
}

// MockEvent_GetEventTime_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEventTime'
type MockEvent_GetEventTime_Call struct {
	*mock.Call
}

// GetEventTime is a helper method to define mock.On call
func (_e *MockEvent_Expecter) GetEventTime() *MockEvent_GetEventTime_Call {
	return &MockEvent_GetEventTime_Call{Call: _e.mock.On("GetEventTime")}
}

func (_c *MockEvent_GetEventTime_Call) Run(run func()) *MockEvent_GetEventTime_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEvent_GetEventTime_Call) Return(time1 time.Time) *MockEvent_GetEventTime_Call {
	_c.Call.Return(time1)
	return _c
}

func (_c *MockEvent_GetEventTime_Call) RunAndReturn(run func() time.Time) *MockEvent_GetEventTime_Call {
	_c.Call.Return(run)
	return _c
}

// Type provides a mock function for the type MockEvent
func (_mock *MockEvent) Type() common.EventType {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Type")
	}

	var r0 common.EventType
	if returnFunc, ok := ret.Get(0).(func() common.EventType); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(common.EventType)
	}
	return r0
}

// MockEvent_Type_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Type'
type MockEvent_Type_Call struct {
	*mock.Call
}

// Type is a helper method to define mock.On call
func (_e *MockEvent_Expecter) Type() *MockEvent_Type_Call {
	return &MockEvent_Type_Call{Call: _e.mock.On("Type")}
}

func (_c *MockEvent_Type_Call) Run(run func()) *MockEvent_Type_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEvent_Type_Call) Return(eventType common.EventType) *MockEvent_Type_Call {
	_c.Call.Return(eventType)
	return _c
}

func (_c *MockEvent_Type_Call) RunAndReturn(run func() common.EventType) *MockEvent_Type_Call {
	_c.Call.Return(run)
	return _c
}

// TypeString provides a mock function for the type MockEvent
func (_mock *MockEvent) TypeString() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for TypeString")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockEvent_TypeString_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TypeString'
type MockEvent_TypeString_Call struct {
	*mock.Call
}

// TypeString is a helper method to define mock.On call
func (_e *MockEvent_Expecter) TypeString() *MockEvent_TypeString_Call {
	return &MockEvent_TypeString_Call{Call: _e.mock.On("TypeString")}
}

func (_c *MockEvent_TypeString_Call) Run(run func()) *MockEvent_TypeString_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEvent_TypeString_Call) Return(s string) *MockEvent_TypeString_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockEvent_TypeString_Call) RunAndReturn(run func() string) *MockEvent_TypeString_Call {
	_c.Call.Return(run)
	return _c
}
