// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package transaction

import (
	"context"
	"time"

	"github.com/LFDT-Paladin/paladin/core/internal/components"
	"github.com/LFDT-Paladin/paladin/core/internal/sequencer/common"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockEvent creates a new instance of MockEvent. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEvent(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEvent {
	mock := &MockEvent{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockEvent is an autogenerated mock type for the Event type
type MockEvent struct {
	mock.Mock
}

type MockEvent_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEvent) EXPECT() *MockEvent_Expecter {
	return &MockEvent_Expecter{mock: &_m.Mock}
}

// GetEventTime provides a mock function for the type MockEvent
func (_mock *MockEvent) GetEventTime() time.Time {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetEventTime")
	}

	var r0 time.Time
	if returnFunc, ok := ret.Get(0).(func() time.Time); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(time.Time)
	}
	return r0
}

// MockEvent_GetEventTime_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEventTime'
type MockEvent_GetEventTime_Call struct {
	*mock.Call
}

// GetEventTime is a helper method to define mock.On call
func (_e *MockEvent_Expecter) GetEventTime() *MockEvent_GetEventTime_Call {
	return &MockEvent_GetEventTime_Call{Call: _e.mock.On("GetEventTime")}
}

func (_c *MockEvent_GetEventTime_Call) Run(run func()) *MockEvent_GetEventTime_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEvent_GetEventTime_Call) Return(time1 time.Time) *MockEvent_GetEventTime_Call {
	_c.Call.Return(time1)
	return _c
}

func (_c *MockEvent_GetEventTime_Call) RunAndReturn(run func() time.Time) *MockEvent_GetEventTime_Call {
	_c.Call.Return(run)
	return _c
}

// GetTransactionID provides a mock function for the type MockEvent
func (_mock *MockEvent) GetTransactionID() uuid.UUID {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetTransactionID")
	}

	var r0 uuid.UUID
	if returnFunc, ok := ret.Get(0).(func() uuid.UUID); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}
	return r0
}

// MockEvent_GetTransactionID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTransactionID'
type MockEvent_GetTransactionID_Call struct {
	*mock.Call
}

// GetTransactionID is a helper method to define mock.On call
func (_e *MockEvent_Expecter) GetTransactionID() *MockEvent_GetTransactionID_Call {
	return &MockEvent_GetTransactionID_Call{Call: _e.mock.On("GetTransactionID")}
}

func (_c *MockEvent_GetTransactionID_Call) Run(run func()) *MockEvent_GetTransactionID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEvent_GetTransactionID_Call) Return(uUID uuid.UUID) *MockEvent_GetTransactionID_Call {
	_c.Call.Return(uUID)
	return _c
}

func (_c *MockEvent_GetTransactionID_Call) RunAndReturn(run func() uuid.UUID) *MockEvent_GetTransactionID_Call {
	_c.Call.Return(run)
	return _c
}

// Type provides a mock function for the type MockEvent
func (_mock *MockEvent) Type() common.EventType {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Type")
	}

	var r0 common.EventType
	if returnFunc, ok := ret.Get(0).(func() common.EventType); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(common.EventType)
	}
	return r0
}

// MockEvent_Type_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Type'
type MockEvent_Type_Call struct {
	*mock.Call
}

// Type is a helper method to define mock.On call
func (_e *MockEvent_Expecter) Type() *MockEvent_Type_Call {
	return &MockEvent_Type_Call{Call: _e.mock.On("Type")}
}

func (_c *MockEvent_Type_Call) Run(run func()) *MockEvent_Type_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEvent_Type_Call) Return(eventType common.EventType) *MockEvent_Type_Call {
	_c.Call.Return(eventType)
	return _c
}

func (_c *MockEvent_Type_Call) RunAndReturn(run func() common.EventType) *MockEvent_Type_Call {
	_c.Call.Return(run)
	return _c
}

// TypeString provides a mock function for the type MockEvent
func (_mock *MockEvent) TypeString() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for TypeString")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockEvent_TypeString_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TypeString'
type MockEvent_TypeString_Call struct {
	*mock.Call
}

// TypeString is a helper method to define mock.On call
func (_e *MockEvent_Expecter) TypeString() *MockEvent_TypeString_Call {
	return &MockEvent_TypeString_Call{Call: _e.mock.On("TypeString")}
}

func (_c *MockEvent_TypeString_Call) Run(run func()) *MockEvent_TypeString_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEvent_TypeString_Call) Return(s string) *MockEvent_TypeString_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockEvent_TypeString_Call) RunAndReturn(run func() string) *MockEvent_TypeString_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCoordinatorTransaction creates a new instance of MockCoordinatorTransaction. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCoordinatorTransaction(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCoordinatorTransaction {
	mock := &MockCoordinatorTransaction{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCoordinatorTransaction is an autogenerated mock type for the CoordinatorTransaction type
type MockCoordinatorTransaction struct {
	mock.Mock
}

type MockCoordinatorTransaction_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCoordinatorTransaction) EXPECT() *MockCoordinatorTransaction_Expecter {
	return &MockCoordinatorTransaction_Expecter{mock: &_m.Mock}
}

// DependentsMustWait provides a mock function for the type MockCoordinatorTransaction
func (_mock *MockCoordinatorTransaction) DependentsMustWait() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for DependentsMustWait")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockCoordinatorTransaction_DependentsMustWait_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DependentsMustWait'
type MockCoordinatorTransaction_DependentsMustWait_Call struct {
	*mock.Call
}

// DependentsMustWait is a helper method to define mock.On call
func (_e *MockCoordinatorTransaction_Expecter) DependentsMustWait() *MockCoordinatorTransaction_DependentsMustWait_Call {
	return &MockCoordinatorTransaction_DependentsMustWait_Call{Call: _e.mock.On("DependentsMustWait")}
}

func (_c *MockCoordinatorTransaction_DependentsMustWait_Call) Run(run func()) *MockCoordinatorTransaction_DependentsMustWait_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCoordinatorTransaction_DependentsMustWait_Call) Return(b bool) *MockCoordinatorTransaction_DependentsMustWait_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockCoordinatorTransaction_DependentsMustWait_Call) RunAndReturn(run func() bool) *MockCoordinatorTransaction_DependentsMustWait_Call {
	_c.Call.Return(run)
	return _c
}

// GetCurrentState provides a mock function for the type MockCoordinatorTransaction
func (_mock *MockCoordinatorTransaction) GetCurrentState() State {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetCurrentState")
	}

	var r0 State
	if returnFunc, ok := ret.Get(0).(func() State); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(State)
	}
	return r0
}

// MockCoordinatorTransaction_GetCurrentState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCurrentState'
type MockCoordinatorTransaction_GetCurrentState_Call struct {
	*mock.Call
}

// GetCurrentState is a helper method to define mock.On call
func (_e *MockCoordinatorTransaction_Expecter) GetCurrentState() *MockCoordinatorTransaction_GetCurrentState_Call {
	return &MockCoordinatorTransaction_GetCurrentState_Call{Call: _e.mock.On("GetCurrentState")}
}

func (_c *MockCoordinatorTransaction_GetCurrentState_Call) Run(run func()) *MockCoordinatorTransaction_GetCurrentState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCoordinatorTransaction_GetCurrentState_Call) Return(state State) *MockCoordinatorTransaction_GetCurrentState_Call {
	_c.Call.Return(state)
	return _c
}

func (_c *MockCoordinatorTransaction_GetCurrentState_Call) RunAndReturn(run func() State) *MockCoordinatorTransaction_GetCurrentState_Call {
	_c.Call.Return(run)
	return _c
}

// GetID provides a mock function for the type MockCoordinatorTransaction
func (_mock *MockCoordinatorTransaction) GetID() uuid.UUID {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetID")
	}

	var r0 uuid.UUID
	if returnFunc, ok := ret.Get(0).(func() uuid.UUID); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}
	return r0
}

// MockCoordinatorTransaction_GetID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetID'
type MockCoordinatorTransaction_GetID_Call struct {
	*mock.Call
}

// GetID is a helper method to define mock.On call
func (_e *MockCoordinatorTransaction_Expecter) GetID() *MockCoordinatorTransaction_GetID_Call {
	return &MockCoordinatorTransaction_GetID_Call{Call: _e.mock.On("GetID")}
}

func (_c *MockCoordinatorTransaction_GetID_Call) Run(run func()) *MockCoordinatorTransaction_GetID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCoordinatorTransaction_GetID_Call) Return(uUID uuid.UUID) *MockCoordinatorTransaction_GetID_Call {
	_c.Call.Return(uUID)
	return _c
}

func (_c *MockCoordinatorTransaction_GetID_Call) RunAndReturn(run func() uuid.UUID) *MockCoordinatorTransaction_GetID_Call {
	_c.Call.Return(run)
	return _c
}

// GetPrivateTransaction provides a mock function for the type MockCoordinatorTransaction
func (_mock *MockCoordinatorTransaction) GetPrivateTransaction() *components.PrivateTransaction {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetPrivateTransaction")
	}

	var r0 *components.PrivateTransaction
	if returnFunc, ok := ret.Get(0).(func() *components.PrivateTransaction); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*components.PrivateTransaction)
		}
	}
	return r0
}

// MockCoordinatorTransaction_GetPrivateTransaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPrivateTransaction'
type MockCoordinatorTransaction_GetPrivateTransaction_Call struct {
	*mock.Call
}

// GetPrivateTransaction is a helper method to define mock.On call
func (_e *MockCoordinatorTransaction_Expecter) GetPrivateTransaction() *MockCoordinatorTransaction_GetPrivateTransaction_Call {
	return &MockCoordinatorTransaction_GetPrivateTransaction_Call{Call: _e.mock.On("GetPrivateTransaction")}
}

func (_c *MockCoordinatorTransaction_GetPrivateTransaction_Call) Run(run func()) *MockCoordinatorTransaction_GetPrivateTransaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCoordinatorTransaction_GetPrivateTransaction_Call) Return(privateTransaction *components.PrivateTransaction) *MockCoordinatorTransaction_GetPrivateTransaction_Call {
	_c.Call.Return(privateTransaction)
	return _c
}

func (_c *MockCoordinatorTransaction_GetPrivateTransaction_Call) RunAndReturn(run func() *components.PrivateTransaction) *MockCoordinatorTransaction_GetPrivateTransaction_Call {
	_c.Call.Return(run)
	return _c
}

// GetSnapshot provides a mock function for the type MockCoordinatorTransaction
func (_mock *MockCoordinatorTransaction) GetSnapshot(ctx context.Context) (*common.SnapshotPooledTransaction, *common.SnapshotDispatchedTransaction, *common.SnapshotConfirmedTransaction) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetSnapshot")
	}

	var r0 *common.SnapshotPooledTransaction
	var r1 *common.SnapshotDispatchedTransaction
	var r2 *common.SnapshotConfirmedTransaction
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*common.SnapshotPooledTransaction, *common.SnapshotDispatchedTransaction, *common.SnapshotConfirmedTransaction)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *common.SnapshotPooledTransaction); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*common.SnapshotPooledTransaction)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) *common.SnapshotDispatchedTransaction); ok {
		r1 = returnFunc(ctx)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*common.SnapshotDispatchedTransaction)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context) *common.SnapshotConfirmedTransaction); ok {
		r2 = returnFunc(ctx)
	} else {
		if ret.Get(2) != nil {
			r2 = ret.Get(2).(*common.SnapshotConfirmedTransaction)
		}
	}
	return r0, r1, r2
}

// MockCoordinatorTransaction_GetSnapshot_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSnapshot'
type MockCoordinatorTransaction_GetSnapshot_Call struct {
	*mock.Call
}

// GetSnapshot is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockCoordinatorTransaction_Expecter) GetSnapshot(ctx interface{}) *MockCoordinatorTransaction_GetSnapshot_Call {
	return &MockCoordinatorTransaction_GetSnapshot_Call{Call: _e.mock.On("GetSnapshot", ctx)}
}

func (_c *MockCoordinatorTransaction_GetSnapshot_Call) Run(run func(ctx context.Context)) *MockCoordinatorTransaction_GetSnapshot_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCoordinatorTransaction_GetSnapshot_Call) Return(snapshotPooledTransaction *common.SnapshotPooledTransaction, snapshotDispatchedTransaction *common.SnapshotDispatchedTransaction, snapshotConfirmedTransaction *common.SnapshotConfirmedTransaction) *MockCoordinatorTransaction_GetSnapshot_Call {
	_c.Call.Return(snapshotPooledTransaction, snapshotDispatchedTransaction, snapshotConfirmedTransaction)
	return _c
}

func (_c *MockCoordinatorTransaction_GetSnapshot_Call) RunAndReturn(run func(ctx context.Context) (*common.SnapshotPooledTransaction, *common.SnapshotDispatchedTransaction, *common.SnapshotConfirmedTransaction)) *MockCoordinatorTransaction_GetSnapshot_Call {
	_c.Call.Return(run)
	return _c
}

// HandleEvent provides a mock function for the type MockCoordinatorTransaction
func (_mock *MockCoordinatorTransaction) HandleEvent(ctx context.Context, event common.Event) error {
	ret := _mock.Called(ctx, event)

	if len(ret) == 0 {
		panic("no return value specified for HandleEvent")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, common.Event) error); ok {
		r0 = returnFunc(ctx, event)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCoordinatorTransaction_HandleEvent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleEvent'
type MockCoordinatorTransaction_HandleEvent_Call struct {
	*mock.Call
}

// HandleEvent is a helper method to define mock.On call
//   - ctx context.Context
//   - event common.Event
func (_e *MockCoordinatorTransaction_Expecter) HandleEvent(ctx interface{}, event interface{}) *MockCoordinatorTransaction_HandleEvent_Call {
	return &MockCoordinatorTransaction_HandleEvent_Call{Call: _e.mock.On("HandleEvent", ctx, event)}
}

func (_c *MockCoordinatorTransaction_HandleEvent_Call) Run(run func(ctx context.Context, event common.Event)) *MockCoordinatorTransaction_HandleEvent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 common.Event
		if args[1] != nil {
			arg1 = args[1].(common.Event)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCoordinatorTransaction_HandleEvent_Call) Return(err error) *MockCoordinatorTransaction_HandleEvent_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCoordinatorTransaction_HandleEvent_Call) RunAndReturn(run func(ctx context.Context, event common.Event) error) *MockCoordinatorTransaction_HandleEvent_Call {
	_c.Call.Return(run)
	return _c
}

// HasDispatchedPublicTransaction provides a mock function for the type MockCoordinatorTransaction
func (_mock *MockCoordinatorTransaction) HasDispatchedPublicTransaction() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for HasDispatchedPublicTransaction")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockCoordinatorTransaction_HasDispatchedPublicTransaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HasDispatchedPublicTransaction'
type MockCoordinatorTransaction_HasDispatchedPublicTransaction_Call struct {
	*mock.Call
}

// HasDispatchedPublicTransaction is a helper method to define mock.On call
func (_e *MockCoordinatorTransaction_Expecter) HasDispatchedPublicTransaction() *MockCoordinatorTransaction_HasDispatchedPublicTransaction_Call {
	return &MockCoordinatorTransaction_HasDispatchedPublicTransaction_Call{Call: _e.mock.On("HasDispatchedPublicTransaction")}
}

func (_c *MockCoordinatorTransaction_HasDispatchedPublicTransaction_Call) Run(run func()) *MockCoordinatorTransaction_HasDispatchedPublicTransaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCoordinatorTransaction_HasDispatchedPublicTransaction_Call) Return(b bool) *MockCoordinatorTransaction_HasDispatchedPublicTransaction_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockCoordinatorTransaction_HasDispatchedPublicTransaction_Call) RunAndReturn(run func() bool) *MockCoordinatorTransaction_HasDispatchedPublicTransaction_Call {
	_c.Call.Return(run)
	return _c
}
