/*
 * Copyright © 2024 Kaleido, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
 * the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
 * an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations under the License.
 *
 * SPDX-License-Identifier: Apache-2.0
 */

package noto

import (
	"context"

	"github.com/LFDT-Paladin/paladin/domains/noto/pkg/types"
	"github.com/LFDT-Paladin/paladin/sdk/go/pkg/pldtypes"
	"github.com/LFDT-Paladin/paladin/toolkit/pkg/prototk"
)

type manifestBuilder struct {
	n *Noto
	preparedOutputs
	preparedLockedOutputs
	infoDistribution identityList
	infoStates       []*prototk.NewState
	// The Noto manifest currently only includes the new states generated by the transactions (outputs & info).
	// The assertion is that the input states are known already by all parties who require them (sender and notary).
}

func (n *Noto) newManifestBuilder(infoDistribution identityList) *manifestBuilder {
	return &manifestBuilder{
		n:                n,
		infoDistribution: infoDistribution,
	}
}

func (mb *manifestBuilder) addOutputs(po *preparedOutputs) *manifestBuilder {
	mb.preparedOutputs.distributions = append(mb.preparedOutputs.distributions, po.distributions...)
	mb.preparedOutputs.coins = append(mb.preparedOutputs.coins, po.coins...)
	mb.preparedOutputs.states = append(mb.preparedOutputs.states, po.states...)
	return mb
}

func (mb *manifestBuilder) addLockedOutputs(po *preparedLockedOutputs) *manifestBuilder {
	mb.preparedLockedOutputs.distributions = append(mb.preparedLockedOutputs.distributions, po.distributions...)
	mb.preparedLockedOutputs.coins = append(mb.preparedLockedOutputs.coins, po.coins...)
	mb.preparedLockedOutputs.states = append(mb.preparedLockedOutputs.states, po.states...)
	return mb
}

func (mb *manifestBuilder) addInfoStates(info ...*prototk.NewState) *manifestBuilder {
	mb.infoStates = append(mb.infoStates, info...)
	return mb
}

func (mb *manifestBuilder) finalizeNewState(manifest *types.NotoManifest, newState *prototk.NewState, distribution identityList) error {
	stateID, err := pldtypes.ParseBytes32(*newState.Id)
	if err == nil {
		manifest.States = append(manifest.States, &types.NotoManifestStateEntry{
			ID:           stateID,
			Participants: distribution.addresses(),
		})
	}
	return err
}

func (mb *manifestBuilder) buildManifest(ctx context.Context, stateQueryContext string) (*prototk.NewState, error) {

	// Build a list of all the new states
	totalStateCount := len(mb.infoStates) + len(mb.preparedOutputs.states) + len(mb.preparedLockedOutputs.states)
	allNewStates := make([]*prototk.NewState, 0, totalStateCount)
	allNewStates = append(allNewStates, mb.infoStates...)
	allNewStates = append(allNewStates, mb.preparedOutputs.states...)
	allNewStates = append(allNewStates, mb.preparedLockedOutputs.states...)

	// Send them to Paladin to validate and generate the IDs
	validatedStates, err := mb.n.Callbacks.ValidateStates(ctx, &prototk.ValidateStatesRequest{
		StateQueryContext: stateQueryContext,
		States:            allNewStates,
	})
	if err != nil {
		return nil, err
	}

	// Store the IDs back into the objects - we do this because it means we'll send them down
	// to Paladin as a result of the assemble, and that
	for i, vs := range validatedStates.States {
		generatedID := vs.Id
		allNewStates[i].Id = &generatedID
	}

	// Build the manifest object
	manifest := &types.NotoManifest{
		Salt:   pldtypes.RandBytes32(),
		States: make([]*types.NotoManifestStateEntry, 0, totalStateCount),
	}
	for _, infoState := range mb.infoStates {
		if err == nil {
			err = mb.finalizeNewState(manifest, infoState, mb.infoDistribution)
		}
	}
	for i := range mb.preparedOutputs.states {
		if err == nil {
			err = mb.finalizeNewState(manifest, mb.preparedOutputs.states[i], mb.preparedOutputs.distributions[i])
		}
	}
	for i := range mb.preparedLockedOutputs.states {
		if err == nil {
			err = mb.finalizeNewState(manifest, mb.preparedLockedOutputs.states[i], mb.preparedLockedOutputs.distributions[i])
		}
	}
	return mb.n.makeNewManifestInfoState(manifest, mb.infoDistribution.identities())
}
