// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package originator

import (
	"context"
	"time"

	"github.com/LFDT-Paladin/paladin/core/internal/components"
	"github.com/LFDT-Paladin/paladin/core/internal/sequencer/common"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockEvent creates a new instance of MockEvent. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEvent(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEvent {
	mock := &MockEvent{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockEvent is an autogenerated mock type for the Event type
type MockEvent struct {
	mock.Mock
}

type MockEvent_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEvent) EXPECT() *MockEvent_Expecter {
	return &MockEvent_Expecter{mock: &_m.Mock}
}

// GetEventTime provides a mock function for the type MockEvent
func (_mock *MockEvent) GetEventTime() time.Time {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetEventTime")
	}

	var r0 time.Time
	if returnFunc, ok := ret.Get(0).(func() time.Time); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(time.Time)
	}
	return r0
}

// MockEvent_GetEventTime_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEventTime'
type MockEvent_GetEventTime_Call struct {
	*mock.Call
}

// GetEventTime is a helper method to define mock.On call
func (_e *MockEvent_Expecter) GetEventTime() *MockEvent_GetEventTime_Call {
	return &MockEvent_GetEventTime_Call{Call: _e.mock.On("GetEventTime")}
}

func (_c *MockEvent_GetEventTime_Call) Run(run func()) *MockEvent_GetEventTime_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEvent_GetEventTime_Call) Return(time1 time.Time) *MockEvent_GetEventTime_Call {
	_c.Call.Return(time1)
	return _c
}

func (_c *MockEvent_GetEventTime_Call) RunAndReturn(run func() time.Time) *MockEvent_GetEventTime_Call {
	_c.Call.Return(run)
	return _c
}

// Type provides a mock function for the type MockEvent
func (_mock *MockEvent) Type() common.EventType {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Type")
	}

	var r0 common.EventType
	if returnFunc, ok := ret.Get(0).(func() common.EventType); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(common.EventType)
	}
	return r0
}

// MockEvent_Type_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Type'
type MockEvent_Type_Call struct {
	*mock.Call
}

// Type is a helper method to define mock.On call
func (_e *MockEvent_Expecter) Type() *MockEvent_Type_Call {
	return &MockEvent_Type_Call{Call: _e.mock.On("Type")}
}

func (_c *MockEvent_Type_Call) Run(run func()) *MockEvent_Type_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEvent_Type_Call) Return(eventType common.EventType) *MockEvent_Type_Call {
	_c.Call.Return(eventType)
	return _c
}

func (_c *MockEvent_Type_Call) RunAndReturn(run func() common.EventType) *MockEvent_Type_Call {
	_c.Call.Return(run)
	return _c
}

// TypeString provides a mock function for the type MockEvent
func (_mock *MockEvent) TypeString() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for TypeString")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockEvent_TypeString_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TypeString'
type MockEvent_TypeString_Call struct {
	*mock.Call
}

// TypeString is a helper method to define mock.On call
func (_e *MockEvent_Expecter) TypeString() *MockEvent_TypeString_Call {
	return &MockEvent_TypeString_Call{Call: _e.mock.On("TypeString")}
}

func (_c *MockEvent_TypeString_Call) Run(run func()) *MockEvent_TypeString_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEvent_TypeString_Call) Return(s string) *MockEvent_TypeString_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockEvent_TypeString_Call) RunAndReturn(run func() string) *MockEvent_TypeString_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSeqOriginator creates a new instance of MockSeqOriginator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSeqOriginator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSeqOriginator {
	mock := &MockSeqOriginator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSeqOriginator is an autogenerated mock type for the SeqOriginator type
type MockSeqOriginator struct {
	mock.Mock
}

type MockSeqOriginator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSeqOriginator) EXPECT() *MockSeqOriginator_Expecter {
	return &MockSeqOriginator_Expecter{mock: &_m.Mock}
}

// GetCurrentCoordinator provides a mock function for the type MockSeqOriginator
func (_mock *MockSeqOriginator) GetCurrentCoordinator() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetCurrentCoordinator")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockSeqOriginator_GetCurrentCoordinator_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCurrentCoordinator'
type MockSeqOriginator_GetCurrentCoordinator_Call struct {
	*mock.Call
}

// GetCurrentCoordinator is a helper method to define mock.On call
func (_e *MockSeqOriginator_Expecter) GetCurrentCoordinator() *MockSeqOriginator_GetCurrentCoordinator_Call {
	return &MockSeqOriginator_GetCurrentCoordinator_Call{Call: _e.mock.On("GetCurrentCoordinator")}
}

func (_c *MockSeqOriginator_GetCurrentCoordinator_Call) Run(run func()) *MockSeqOriginator_GetCurrentCoordinator_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSeqOriginator_GetCurrentCoordinator_Call) Return(s string) *MockSeqOriginator_GetCurrentCoordinator_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockSeqOriginator_GetCurrentCoordinator_Call) RunAndReturn(run func() string) *MockSeqOriginator_GetCurrentCoordinator_Call {
	_c.Call.Return(run)
	return _c
}

// GetTxStatus provides a mock function for the type MockSeqOriginator
func (_mock *MockSeqOriginator) GetTxStatus(ctx context.Context, txID uuid.UUID) (components.PrivateTxStatus, error) {
	ret := _mock.Called(ctx, txID)

	if len(ret) == 0 {
		panic("no return value specified for GetTxStatus")
	}

	var r0 components.PrivateTxStatus
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (components.PrivateTxStatus, error)); ok {
		return returnFunc(ctx, txID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) components.PrivateTxStatus); ok {
		r0 = returnFunc(ctx, txID)
	} else {
		r0 = ret.Get(0).(components.PrivateTxStatus)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, txID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSeqOriginator_GetTxStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTxStatus'
type MockSeqOriginator_GetTxStatus_Call struct {
	*mock.Call
}

// GetTxStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - txID uuid.UUID
func (_e *MockSeqOriginator_Expecter) GetTxStatus(ctx interface{}, txID interface{}) *MockSeqOriginator_GetTxStatus_Call {
	return &MockSeqOriginator_GetTxStatus_Call{Call: _e.mock.On("GetTxStatus", ctx, txID)}
}

func (_c *MockSeqOriginator_GetTxStatus_Call) Run(run func(ctx context.Context, txID uuid.UUID)) *MockSeqOriginator_GetTxStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSeqOriginator_GetTxStatus_Call) Return(status components.PrivateTxStatus, err error) *MockSeqOriginator_GetTxStatus_Call {
	_c.Call.Return(status, err)
	return _c
}

func (_c *MockSeqOriginator_GetTxStatus_Call) RunAndReturn(run func(ctx context.Context, txID uuid.UUID) (components.PrivateTxStatus, error)) *MockSeqOriginator_GetTxStatus_Call {
	_c.Call.Return(run)
	return _c
}

// QueueEvent provides a mock function for the type MockSeqOriginator
func (_mock *MockSeqOriginator) QueueEvent(ctx context.Context, event common.Event) {
	_mock.Called(ctx, event)
	return
}

// MockSeqOriginator_QueueEvent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'QueueEvent'
type MockSeqOriginator_QueueEvent_Call struct {
	*mock.Call
}

// QueueEvent is a helper method to define mock.On call
//   - ctx context.Context
//   - event common.Event
func (_e *MockSeqOriginator_Expecter) QueueEvent(ctx interface{}, event interface{}) *MockSeqOriginator_QueueEvent_Call {
	return &MockSeqOriginator_QueueEvent_Call{Call: _e.mock.On("QueueEvent", ctx, event)}
}

func (_c *MockSeqOriginator_QueueEvent_Call) Run(run func(ctx context.Context, event common.Event)) *MockSeqOriginator_QueueEvent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 common.Event
		if args[1] != nil {
			arg1 = args[1].(common.Event)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSeqOriginator_QueueEvent_Call) Return() *MockSeqOriginator_QueueEvent_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockSeqOriginator_QueueEvent_Call) RunAndReturn(run func(ctx context.Context, event common.Event)) *MockSeqOriginator_QueueEvent_Call {
	_c.Run(run)
	return _c
}

// SetActiveCoordinator provides a mock function for the type MockSeqOriginator
func (_mock *MockSeqOriginator) SetActiveCoordinator(ctx context.Context, coordinator string) error {
	ret := _mock.Called(ctx, coordinator)

	if len(ret) == 0 {
		panic("no return value specified for SetActiveCoordinator")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, coordinator)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSeqOriginator_SetActiveCoordinator_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetActiveCoordinator'
type MockSeqOriginator_SetActiveCoordinator_Call struct {
	*mock.Call
}

// SetActiveCoordinator is a helper method to define mock.On call
//   - ctx context.Context
//   - coordinator string
func (_e *MockSeqOriginator_Expecter) SetActiveCoordinator(ctx interface{}, coordinator interface{}) *MockSeqOriginator_SetActiveCoordinator_Call {
	return &MockSeqOriginator_SetActiveCoordinator_Call{Call: _e.mock.On("SetActiveCoordinator", ctx, coordinator)}
}

func (_c *MockSeqOriginator_SetActiveCoordinator_Call) Run(run func(ctx context.Context, coordinator string)) *MockSeqOriginator_SetActiveCoordinator_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSeqOriginator_SetActiveCoordinator_Call) Return(err error) *MockSeqOriginator_SetActiveCoordinator_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSeqOriginator_SetActiveCoordinator_Call) RunAndReturn(run func(ctx context.Context, coordinator string) error) *MockSeqOriginator_SetActiveCoordinator_Call {
	_c.Call.Return(run)
	return _c
}

// Stop provides a mock function for the type MockSeqOriginator
func (_mock *MockSeqOriginator) Stop() {
	_mock.Called()
	return
}

// MockSeqOriginator_Stop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stop'
type MockSeqOriginator_Stop_Call struct {
	*mock.Call
}

// Stop is a helper method to define mock.On call
func (_e *MockSeqOriginator_Expecter) Stop() *MockSeqOriginator_Stop_Call {
	return &MockSeqOriginator_Stop_Call{Call: _e.mock.On("Stop")}
}

func (_c *MockSeqOriginator_Stop_Call) Run(run func()) *MockSeqOriginator_Stop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSeqOriginator_Stop_Call) Return() *MockSeqOriginator_Stop_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockSeqOriginator_Stop_Call) RunAndReturn(run func()) *MockSeqOriginator_Stop_Call {
	_c.Run(run)
	return _c
}
