// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package ptmgrtypes

import (
	"context"

	"github.com/LFDT-Paladin/paladin/core/internal/components"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockTransactionFlow creates a new instance of MockTransactionFlow. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTransactionFlow(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTransactionFlow {
	mock := &MockTransactionFlow{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTransactionFlow is an autogenerated mock type for the TransactionFlow type
type MockTransactionFlow struct {
	mock.Mock
}

type MockTransactionFlow_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTransactionFlow) EXPECT() *MockTransactionFlow_Expecter {
	return &MockTransactionFlow_Expecter{mock: &_m.Mock}
}

// Action provides a mock function for the type MockTransactionFlow
func (_mock *MockTransactionFlow) Action(ctx context.Context) {
	_mock.Called(ctx)
	return
}

// MockTransactionFlow_Action_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Action'
type MockTransactionFlow_Action_Call struct {
	*mock.Call
}

// Action is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockTransactionFlow_Expecter) Action(ctx interface{}) *MockTransactionFlow_Action_Call {
	return &MockTransactionFlow_Action_Call{Call: _e.mock.On("Action", ctx)}
}

func (_c *MockTransactionFlow_Action_Call) Run(run func(ctx context.Context)) *MockTransactionFlow_Action_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTransactionFlow_Action_Call) Return() *MockTransactionFlow_Action_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockTransactionFlow_Action_Call) RunAndReturn(run func(ctx context.Context)) *MockTransactionFlow_Action_Call {
	_c.Run(run)
	return _c
}

// ApplyEvent provides a mock function for the type MockTransactionFlow
func (_mock *MockTransactionFlow) ApplyEvent(ctx context.Context, event PrivateTransactionEvent) {
	_mock.Called(ctx, event)
	return
}

// MockTransactionFlow_ApplyEvent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ApplyEvent'
type MockTransactionFlow_ApplyEvent_Call struct {
	*mock.Call
}

// ApplyEvent is a helper method to define mock.On call
//   - ctx context.Context
//   - event PrivateTransactionEvent
func (_e *MockTransactionFlow_Expecter) ApplyEvent(ctx interface{}, event interface{}) *MockTransactionFlow_ApplyEvent_Call {
	return &MockTransactionFlow_ApplyEvent_Call{Call: _e.mock.On("ApplyEvent", ctx, event)}
}

func (_c *MockTransactionFlow_ApplyEvent_Call) Run(run func(ctx context.Context, event PrivateTransactionEvent)) *MockTransactionFlow_ApplyEvent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 PrivateTransactionEvent
		if args[1] != nil {
			arg1 = args[1].(PrivateTransactionEvent)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTransactionFlow_ApplyEvent_Call) Return() *MockTransactionFlow_ApplyEvent_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockTransactionFlow_ApplyEvent_Call) RunAndReturn(run func(ctx context.Context, event PrivateTransactionEvent)) *MockTransactionFlow_ApplyEvent_Call {
	_c.Run(run)
	return _c
}

// CoordinatingLocally provides a mock function for the type MockTransactionFlow
func (_mock *MockTransactionFlow) CoordinatingLocally(ctx context.Context) bool {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for CoordinatingLocally")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(context.Context) bool); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockTransactionFlow_CoordinatingLocally_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CoordinatingLocally'
type MockTransactionFlow_CoordinatingLocally_Call struct {
	*mock.Call
}

// CoordinatingLocally is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockTransactionFlow_Expecter) CoordinatingLocally(ctx interface{}) *MockTransactionFlow_CoordinatingLocally_Call {
	return &MockTransactionFlow_CoordinatingLocally_Call{Call: _e.mock.On("CoordinatingLocally", ctx)}
}

func (_c *MockTransactionFlow_CoordinatingLocally_Call) Run(run func(ctx context.Context)) *MockTransactionFlow_CoordinatingLocally_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTransactionFlow_CoordinatingLocally_Call) Return(b bool) *MockTransactionFlow_CoordinatingLocally_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockTransactionFlow_CoordinatingLocally_Call) RunAndReturn(run func(ctx context.Context) bool) *MockTransactionFlow_CoordinatingLocally_Call {
	_c.Call.Return(run)
	return _c
}

// DispatchInitiated provides a mock function for the type MockTransactionFlow
func (_mock *MockTransactionFlow) DispatchInitiated(ctx context.Context) bool {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for DispatchInitiated")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(context.Context) bool); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockTransactionFlow_DispatchInitiated_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DispatchInitiated'
type MockTransactionFlow_DispatchInitiated_Call struct {
	*mock.Call
}

// DispatchInitiated is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockTransactionFlow_Expecter) DispatchInitiated(ctx interface{}) *MockTransactionFlow_DispatchInitiated_Call {
	return &MockTransactionFlow_DispatchInitiated_Call{Call: _e.mock.On("DispatchInitiated", ctx)}
}

func (_c *MockTransactionFlow_DispatchInitiated_Call) Run(run func(ctx context.Context)) *MockTransactionFlow_DispatchInitiated_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTransactionFlow_DispatchInitiated_Call) Return(b bool) *MockTransactionFlow_DispatchInitiated_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockTransactionFlow_DispatchInitiated_Call) RunAndReturn(run func(ctx context.Context) bool) *MockTransactionFlow_DispatchInitiated_Call {
	_c.Call.Return(run)
	return _c
}

// GetStateDistributions provides a mock function for the type MockTransactionFlow
func (_mock *MockTransactionFlow) GetStateDistributions(ctx context.Context) (*components.StateDistributionSet, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetStateDistributions")
	}

	var r0 *components.StateDistributionSet
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*components.StateDistributionSet, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *components.StateDistributionSet); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*components.StateDistributionSet)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTransactionFlow_GetStateDistributions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStateDistributions'
type MockTransactionFlow_GetStateDistributions_Call struct {
	*mock.Call
}

// GetStateDistributions is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockTransactionFlow_Expecter) GetStateDistributions(ctx interface{}) *MockTransactionFlow_GetStateDistributions_Call {
	return &MockTransactionFlow_GetStateDistributions_Call{Call: _e.mock.On("GetStateDistributions", ctx)}
}

func (_c *MockTransactionFlow_GetStateDistributions_Call) Run(run func(ctx context.Context)) *MockTransactionFlow_GetStateDistributions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTransactionFlow_GetStateDistributions_Call) Return(stateDistributionSet *components.StateDistributionSet, err error) *MockTransactionFlow_GetStateDistributions_Call {
	_c.Call.Return(stateDistributionSet, err)
	return _c
}

func (_c *MockTransactionFlow_GetStateDistributions_Call) RunAndReturn(run func(ctx context.Context) (*components.StateDistributionSet, error)) *MockTransactionFlow_GetStateDistributions_Call {
	_c.Call.Return(run)
	return _c
}

// GetTxStatus provides a mock function for the type MockTransactionFlow
func (_mock *MockTransactionFlow) GetTxStatus(ctx context.Context) (components.PrivateTxStatus, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetTxStatus")
	}

	var r0 components.PrivateTxStatus
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (components.PrivateTxStatus, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) components.PrivateTxStatus); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(components.PrivateTxStatus)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTransactionFlow_GetTxStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTxStatus'
type MockTransactionFlow_GetTxStatus_Call struct {
	*mock.Call
}

// GetTxStatus is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockTransactionFlow_Expecter) GetTxStatus(ctx interface{}) *MockTransactionFlow_GetTxStatus_Call {
	return &MockTransactionFlow_GetTxStatus_Call{Call: _e.mock.On("GetTxStatus", ctx)}
}

func (_c *MockTransactionFlow_GetTxStatus_Call) Run(run func(ctx context.Context)) *MockTransactionFlow_GetTxStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTransactionFlow_GetTxStatus_Call) Return(privateTxStatus components.PrivateTxStatus, err error) *MockTransactionFlow_GetTxStatus_Call {
	_c.Call.Return(privateTxStatus, err)
	return _c
}

func (_c *MockTransactionFlow_GetTxStatus_Call) RunAndReturn(run func(ctx context.Context) (components.PrivateTxStatus, error)) *MockTransactionFlow_GetTxStatus_Call {
	_c.Call.Return(run)
	return _c
}

// ID provides a mock function for the type MockTransactionFlow
func (_mock *MockTransactionFlow) ID(ctx context.Context) uuid.UUID {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ID")
	}

	var r0 uuid.UUID
	if returnFunc, ok := ret.Get(0).(func(context.Context) uuid.UUID); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}
	return r0
}

// MockTransactionFlow_ID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ID'
type MockTransactionFlow_ID_Call struct {
	*mock.Call
}

// ID is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockTransactionFlow_Expecter) ID(ctx interface{}) *MockTransactionFlow_ID_Call {
	return &MockTransactionFlow_ID_Call{Call: _e.mock.On("ID", ctx)}
}

func (_c *MockTransactionFlow_ID_Call) Run(run func(ctx context.Context)) *MockTransactionFlow_ID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTransactionFlow_ID_Call) Return(uUID uuid.UUID) *MockTransactionFlow_ID_Call {
	_c.Call.Return(uUID)
	return _c
}

func (_c *MockTransactionFlow_ID_Call) RunAndReturn(run func(ctx context.Context) uuid.UUID) *MockTransactionFlow_ID_Call {
	_c.Call.Return(run)
	return _c
}

// InputStateIDs provides a mock function for the type MockTransactionFlow
func (_mock *MockTransactionFlow) InputStateIDs(ctx context.Context) []string {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for InputStateIDs")
	}

	var r0 []string
	if returnFunc, ok := ret.Get(0).(func(context.Context) []string); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	return r0
}

// MockTransactionFlow_InputStateIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InputStateIDs'
type MockTransactionFlow_InputStateIDs_Call struct {
	*mock.Call
}

// InputStateIDs is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockTransactionFlow_Expecter) InputStateIDs(ctx interface{}) *MockTransactionFlow_InputStateIDs_Call {
	return &MockTransactionFlow_InputStateIDs_Call{Call: _e.mock.On("InputStateIDs", ctx)}
}

func (_c *MockTransactionFlow_InputStateIDs_Call) Run(run func(ctx context.Context)) *MockTransactionFlow_InputStateIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTransactionFlow_InputStateIDs_Call) Return(strings []string) *MockTransactionFlow_InputStateIDs_Call {
	_c.Call.Return(strings)
	return _c
}

func (_c *MockTransactionFlow_InputStateIDs_Call) RunAndReturn(run func(ctx context.Context) []string) *MockTransactionFlow_InputStateIDs_Call {
	_c.Call.Return(run)
	return _c
}

// IsComplete provides a mock function for the type MockTransactionFlow
func (_mock *MockTransactionFlow) IsComplete(ctx context.Context) bool {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for IsComplete")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(context.Context) bool); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockTransactionFlow_IsComplete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsComplete'
type MockTransactionFlow_IsComplete_Call struct {
	*mock.Call
}

// IsComplete is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockTransactionFlow_Expecter) IsComplete(ctx interface{}) *MockTransactionFlow_IsComplete_Call {
	return &MockTransactionFlow_IsComplete_Call{Call: _e.mock.On("IsComplete", ctx)}
}

func (_c *MockTransactionFlow_IsComplete_Call) Run(run func(ctx context.Context)) *MockTransactionFlow_IsComplete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTransactionFlow_IsComplete_Call) Return(b bool) *MockTransactionFlow_IsComplete_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockTransactionFlow_IsComplete_Call) RunAndReturn(run func(ctx context.Context) bool) *MockTransactionFlow_IsComplete_Call {
	_c.Call.Return(run)
	return _c
}

// IsEndorsed provides a mock function for the type MockTransactionFlow
func (_mock *MockTransactionFlow) IsEndorsed(ctx context.Context) bool {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for IsEndorsed")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(context.Context) bool); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockTransactionFlow_IsEndorsed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsEndorsed'
type MockTransactionFlow_IsEndorsed_Call struct {
	*mock.Call
}

// IsEndorsed is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockTransactionFlow_Expecter) IsEndorsed(ctx interface{}) *MockTransactionFlow_IsEndorsed_Call {
	return &MockTransactionFlow_IsEndorsed_Call{Call: _e.mock.On("IsEndorsed", ctx)}
}

func (_c *MockTransactionFlow_IsEndorsed_Call) Run(run func(ctx context.Context)) *MockTransactionFlow_IsEndorsed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTransactionFlow_IsEndorsed_Call) Return(b bool) *MockTransactionFlow_IsEndorsed_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockTransactionFlow_IsEndorsed_Call) RunAndReturn(run func(ctx context.Context) bool) *MockTransactionFlow_IsEndorsed_Call {
	_c.Call.Return(run)
	return _c
}

// OutputStateIDs provides a mock function for the type MockTransactionFlow
func (_mock *MockTransactionFlow) OutputStateIDs(ctx context.Context) []string {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for OutputStateIDs")
	}

	var r0 []string
	if returnFunc, ok := ret.Get(0).(func(context.Context) []string); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	return r0
}

// MockTransactionFlow_OutputStateIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OutputStateIDs'
type MockTransactionFlow_OutputStateIDs_Call struct {
	*mock.Call
}

// OutputStateIDs is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockTransactionFlow_Expecter) OutputStateIDs(ctx interface{}) *MockTransactionFlow_OutputStateIDs_Call {
	return &MockTransactionFlow_OutputStateIDs_Call{Call: _e.mock.On("OutputStateIDs", ctx)}
}

func (_c *MockTransactionFlow_OutputStateIDs_Call) Run(run func(ctx context.Context)) *MockTransactionFlow_OutputStateIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTransactionFlow_OutputStateIDs_Call) Return(strings []string) *MockTransactionFlow_OutputStateIDs_Call {
	_c.Call.Return(strings)
	return _c
}

func (_c *MockTransactionFlow_OutputStateIDs_Call) RunAndReturn(run func(ctx context.Context) []string) *MockTransactionFlow_OutputStateIDs_Call {
	_c.Call.Return(run)
	return _c
}

// PrepareTransaction provides a mock function for the type MockTransactionFlow
func (_mock *MockTransactionFlow) PrepareTransaction(ctx context.Context, defaultSigner string) (*components.PrivateTransaction, error) {
	ret := _mock.Called(ctx, defaultSigner)

	if len(ret) == 0 {
		panic("no return value specified for PrepareTransaction")
	}

	var r0 *components.PrivateTransaction
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*components.PrivateTransaction, error)); ok {
		return returnFunc(ctx, defaultSigner)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *components.PrivateTransaction); ok {
		r0 = returnFunc(ctx, defaultSigner)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*components.PrivateTransaction)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, defaultSigner)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTransactionFlow_PrepareTransaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PrepareTransaction'
type MockTransactionFlow_PrepareTransaction_Call struct {
	*mock.Call
}

// PrepareTransaction is a helper method to define mock.On call
//   - ctx context.Context
//   - defaultSigner string
func (_e *MockTransactionFlow_Expecter) PrepareTransaction(ctx interface{}, defaultSigner interface{}) *MockTransactionFlow_PrepareTransaction_Call {
	return &MockTransactionFlow_PrepareTransaction_Call{Call: _e.mock.On("PrepareTransaction", ctx, defaultSigner)}
}

func (_c *MockTransactionFlow_PrepareTransaction_Call) Run(run func(ctx context.Context, defaultSigner string)) *MockTransactionFlow_PrepareTransaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTransactionFlow_PrepareTransaction_Call) Return(privateTransaction *components.PrivateTransaction, err error) *MockTransactionFlow_PrepareTransaction_Call {
	_c.Call.Return(privateTransaction, err)
	return _c
}

func (_c *MockTransactionFlow_PrepareTransaction_Call) RunAndReturn(run func(ctx context.Context, defaultSigner string) (*components.PrivateTransaction, error)) *MockTransactionFlow_PrepareTransaction_Call {
	_c.Call.Return(run)
	return _c
}

// PrivateTransaction provides a mock function for the type MockTransactionFlow
func (_mock *MockTransactionFlow) PrivateTransaction() *components.PrivateTransaction {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for PrivateTransaction")
	}

	var r0 *components.PrivateTransaction
	if returnFunc, ok := ret.Get(0).(func() *components.PrivateTransaction); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*components.PrivateTransaction)
		}
	}
	return r0
}

// MockTransactionFlow_PrivateTransaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PrivateTransaction'
type MockTransactionFlow_PrivateTransaction_Call struct {
	*mock.Call
}

// PrivateTransaction is a helper method to define mock.On call
func (_e *MockTransactionFlow_Expecter) PrivateTransaction() *MockTransactionFlow_PrivateTransaction_Call {
	return &MockTransactionFlow_PrivateTransaction_Call{Call: _e.mock.On("PrivateTransaction")}
}

func (_c *MockTransactionFlow_PrivateTransaction_Call) Run(run func()) *MockTransactionFlow_PrivateTransaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTransactionFlow_PrivateTransaction_Call) Return(privateTransaction *components.PrivateTransaction) *MockTransactionFlow_PrivateTransaction_Call {
	_c.Call.Return(privateTransaction)
	return _c
}

func (_c *MockTransactionFlow_PrivateTransaction_Call) RunAndReturn(run func() *components.PrivateTransaction) *MockTransactionFlow_PrivateTransaction_Call {
	_c.Call.Return(run)
	return _c
}

// ReadyForSequencing provides a mock function for the type MockTransactionFlow
func (_mock *MockTransactionFlow) ReadyForSequencing(ctx context.Context) bool {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ReadyForSequencing")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(context.Context) bool); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockTransactionFlow_ReadyForSequencing_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadyForSequencing'
type MockTransactionFlow_ReadyForSequencing_Call struct {
	*mock.Call
}

// ReadyForSequencing is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockTransactionFlow_Expecter) ReadyForSequencing(ctx interface{}) *MockTransactionFlow_ReadyForSequencing_Call {
	return &MockTransactionFlow_ReadyForSequencing_Call{Call: _e.mock.On("ReadyForSequencing", ctx)}
}

func (_c *MockTransactionFlow_ReadyForSequencing_Call) Run(run func(ctx context.Context)) *MockTransactionFlow_ReadyForSequencing_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTransactionFlow_ReadyForSequencing_Call) Return(b bool) *MockTransactionFlow_ReadyForSequencing_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockTransactionFlow_ReadyForSequencing_Call) RunAndReturn(run func(ctx context.Context) bool) *MockTransactionFlow_ReadyForSequencing_Call {
	_c.Call.Return(run)
	return _c
}

// SetDispatchPending provides a mock function for the type MockTransactionFlow
func (_mock *MockTransactionFlow) SetDispatchPending(ctx context.Context, dispatchPending bool) {
	_mock.Called(ctx, dispatchPending)
	return
}

// MockTransactionFlow_SetDispatchPending_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetDispatchPending'
type MockTransactionFlow_SetDispatchPending_Call struct {
	*mock.Call
}

// SetDispatchPending is a helper method to define mock.On call
//   - ctx context.Context
//   - dispatchPending bool
func (_e *MockTransactionFlow_Expecter) SetDispatchPending(ctx interface{}, dispatchPending interface{}) *MockTransactionFlow_SetDispatchPending_Call {
	return &MockTransactionFlow_SetDispatchPending_Call{Call: _e.mock.On("SetDispatchPending", ctx, dispatchPending)}
}

func (_c *MockTransactionFlow_SetDispatchPending_Call) Run(run func(ctx context.Context, dispatchPending bool)) *MockTransactionFlow_SetDispatchPending_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 bool
		if args[1] != nil {
			arg1 = args[1].(bool)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTransactionFlow_SetDispatchPending_Call) Return() *MockTransactionFlow_SetDispatchPending_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockTransactionFlow_SetDispatchPending_Call) RunAndReturn(run func(ctx context.Context, dispatchPending bool)) *MockTransactionFlow_SetDispatchPending_Call {
	_c.Run(run)
	return _c
}

// Signer provides a mock function for the type MockTransactionFlow
func (_mock *MockTransactionFlow) Signer(ctx context.Context) string {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Signer")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(context.Context) string); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockTransactionFlow_Signer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Signer'
type MockTransactionFlow_Signer_Call struct {
	*mock.Call
}

// Signer is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockTransactionFlow_Expecter) Signer(ctx interface{}) *MockTransactionFlow_Signer_Call {
	return &MockTransactionFlow_Signer_Call{Call: _e.mock.On("Signer", ctx)}
}

func (_c *MockTransactionFlow_Signer_Call) Run(run func(ctx context.Context)) *MockTransactionFlow_Signer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTransactionFlow_Signer_Call) Return(s string) *MockTransactionFlow_Signer_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockTransactionFlow_Signer_Call) RunAndReturn(run func(ctx context.Context) string) *MockTransactionFlow_Signer_Call {
	_c.Call.Return(run)
	return _c
}
